backend:
  name: github
  repo: jasonsutter87/TheSnackAttack

  branch: master # Branch to update (optional; defaults to master)
  
# This line should *not* be indented
publish_mode: editorial_workflow

# These lines should *not* be indented
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "covers"
    label: "Covers"
    folder: "content/covers"
    create: true
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "secondary title", label: "Secondary Title", widget: "string" }
      - { name: "type", label: "Type", widget: "select", options: [ "cover1", "cover2", "cover3", "cover4"] }
      - { name: "images", label: "Images", widget: "list", max: 1, allow_add: true, allow_delete: true, fields: [
          { label: "Image", name: "image", widget: "image" },
          { label: "Caption", name: "caption", widget: "string", required: false }
        ]}

  - name: "recipes"
    label: "Recipes"
    folder: "content/recipes"
    create: true
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "design type", label: "Design Type", widget: "select", options: [ "recipe 1", "recipe 2", "recipe 3", "recipe 4", "recipe 5", "recipe 6", "recipe 7", "recipe 8", "recipe 9", "recipe 10", "recipe 11", "recipe 12", "recipe 13", "recipe 14", "recipe 15", "recipe 16"] }
      - { name: "meal type", label: "Meal Type", widget: "select", options: [ "Breakfast", Pasta", "Meat", "Bread", "desserts"] }
      - { name: "intro", label: "Introduction", widget: "markdown", required: false}
      - { name: "prep_time", label: "Preparation Time (in minutes)", widget: "number" }
      - { name: "cook_time", label: "Cooking Time (in minutes)", widget: "number" }
      - { name: "serves", label: "Number of Servings", widget: "number" }
      - { name: "ingredients", label: "Ingredients", widget: "markdown" }
      - { name: "directions", label: "Directions", widget: "markdown" }
      - { name: "notes", label: "Notes", widget: "markdown", required: false}
      - { name: "images", label: "Images", widget: "list", max: 4, allow_add: true, allow_delete: true, fields: [
          { label: "Image", name: "image", widget: "image" },
          { label: "Caption", name: "caption", widget: "string", required: false }
        ]}

 